project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Eric Mai"
  site-url: "https://ericvmai.com"
  repo-url: "https://github.com/ericvmai/ericvmai"
  favicon: resources/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: More About Me
      - href: resume.qmd
        text: Resume
      - href: portfolio.qmd
        text: Portfolio
      - href: blog.qmd
        text: Blog
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo  # or remove the theme line entirely
    css: fix.css